// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDaO2CUoCfdDSnlgo-JrzKlzO_qkAyVeg',
    appId: '1:908825120304:web:c98c3146529621f2c067f5',
    messagingSenderId: '908825120304',
    projectId: 'kn-restaurant-a9077',
    authDomain: 'kn-restaurant-a9077.firebaseapp.com',
    storageBucket: 'kn-restaurant-a9077.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwjnpuY4OipKjZvoQ0cPpprgmeOou_J8',
    appId: '1:908825120304:android:df036245f7653fa6c067f5',
    messagingSenderId: '908825120304',
    projectId: 'kn-restaurant-a9077',
    storageBucket: 'kn-restaurant-a9077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsemvgO4NSsBVFcH5mlx2LCia-POIufTE',
    appId: '1:908825120304:ios:d7ca1d3eeebbc687c067f5',
    messagingSenderId: '908825120304',
    projectId: 'kn-restaurant-a9077',
    storageBucket: 'kn-restaurant-a9077.appspot.com',
    iosClientId: '908825120304-hkr4s2hon8qv19kdrlg7p2n43cf0mm5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.knRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsemvgO4NSsBVFcH5mlx2LCia-POIufTE',
    appId: '1:908825120304:ios:d7ca1d3eeebbc687c067f5',
    messagingSenderId: '908825120304',
    projectId: 'kn-restaurant-a9077',
    storageBucket: 'kn-restaurant-a9077.appspot.com',
    iosClientId: '908825120304-hkr4s2hon8qv19kdrlg7p2n43cf0mm5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.knRestaurant',
  );
}
